export const FAVORITES_CARD_REQUEST_SUCCESS = 'FAVORITES/CARD/REQUEST_SUCCESS';
export const FAVORITES_CARD_REQUEST_STARTED = 'FAVORITES/CARD/REQUEST_STARTED';
export const FAVORITES_CARD_REQUEST_FAILED = 'FAVORITES/CARD/REQUEST_FAILED';

export const FAVORITES_CARD_ADD = 'FAVORITES/CARD/CREATE';
export const FAVORITES_CARD_DELETE = 'FAVORITES/CARD/DELETE';
export const FAVORITES_CARD_GET_LIST = 'FAVORITES/CARD/GET/LIST';

export const FAVORITES_LOCATION_ADD = 'FAVORITES/LOCATION/CREATE';
export const FAVORITES_LOCATION_DELETE = 'FAVORITES/LOCATION/DELETE';
export const FAVORITES_LOCATION_GET_LIST = 'FAVORITES/LOCATION/GET/LIST';
