export const SUGGESTIONS_SET_SW_DATA = 'SUGGESTIONS/SET/SW_DATA';
export const GET_SUGGESTIONS = 'SUGGESTIONS/LIST';
export const SUGGESTIONS_QUERY_SET = 'SUGGESTIONS/QUERY/SET';
export const CACHED_SUGGESTIONS = 'SUGGESTIONS/CACHE';
export const SUGGESTIONS_REQUEST_STARTED = 'SUGGESTIONS/REQUEST_STARTED';
export const SUGGESTIONS_REQUEST_SUCCESS = 'SUGGESTIONS/REQUEST_SUCCESS';
export const SUGGESTIONS_REQUEST_FAILED = 'SUGGESTIONS/REQUEST_FAILED';
