export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const SUGGESTIONS_REQUEST_STARTED = 'SUGGESTIONS_REQUEST_STARTED';
export const SUGGESTIONS_REQUEST_SUCCESS = 'SUGGESTIONS_REQUEST_SUCCESS';
export const SUGGESTIONS_REQUEST_FAILED = 'SUGGESTIONS_REQUEST_FAILED';
