export const GET_SUGGESTIONS = 'SUGGESTIONS/LIST';
export const SUGGESTIONS_REQUEST_STARTED = 'SUGGESTIONS/REQUEST_STARTED';
export const SUGGESTIONS_REQUEST_SUCCESS = 'SUGGESTIONS/REQUEST_SUCCESS';
export const SUGGESTIONS_REQUEST_FAILED = 'SUGGESTIONS/REQUEST_FAILED';
